#!/usr/bin/env ruby

ONE_LOCATION = ENV["ONE_LOCATION"] if !defined?(ONE_LOCATION)

if !ONE_LOCATION
    RUBY_LIB_LOCATION = "/usr/lib/one/ruby" if !defined?(RUBY_LIB_LOCATION)
else
    RUBY_LIB_LOCATION = ONE_LOCATION + "/lib/ruby" if !defined?(RUBY_LIB_LOCATION)
end

$: << RUBY_LIB_LOCATION
$: << File.dirname(__FILE__)

require 'oci_driver'

deploy_id = ARGV[0]
host      = ARGV[1]

begin
    oci_drv = OCIDriver.new(host)
    oci_drv.cancel(deploy_id)
rescue => e
    OpenNebula.handle_driver_exception("Cancel", e, host, deploy_id)
end
